name: Execute SnowSQL Commands

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute-snowsql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          echo "Updating system and installing dependencies..."
          sudo apt-get update
          sudo apt-get install -y bash curl coreutils

      - name: Install SnowSQL
        run: |
          set -e  # Fail on first error
          
          echo "Downloading SnowSQL installer..."
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.2-linux_x86_64.bash
          
          if [ ! -f snowsql-1.3.2-linux_x86_64.bash ]; then
            echo "Error: SnowSQL installer download failed."
            exit 1
          fi

          chmod +x snowsql-1.3.2-linux_x86_64.bash

          echo "Running SnowSQL installer..."
          ./snowsql-1.3.2-linux_x86_64.bash --debug > snowsql_install.log 2>&1 || { 
            echo "SnowSQL installation failed. See the logs:"; 
            cat snowsql_install.log; 
            exit 1; 
          }
          
          echo "Installation complete. Verifying..."
          snowsql -v || { 
            echo "SnowSQL verification failed."; 
            exit 1; 
          }

      - name: Run SnowSQL Query
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PASSWORD: ${{ secrets.SNOWSQL_PASSWORD }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}
          SNOWSQL_SCHEMA: ${{ secrets.SNOWSQL_SCHEMA }}
        run: |
          echo "Executing SnowSQL query..."
          snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PASSWORD \
            -d $SNOWSQL_DATABASE -w $SNOWSQL_WAREHOUSE -s $SNOWSQL_SCHEMA \
            -f ./run_query.sql
