name: Execute SnowSQL Commands

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  execute-snowsql:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: |
          echo "Updating system and installing required dependencies..."
          sudo apt-get update
          sudo apt-get install -y bash curl libssl-dev libffi-dev coreutils

      # Step 5: Run SnowSQL Query
      - name: Run SnowSQL Query
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PASSWORD: ${{ secrets.SNOWSQL_PASSWORD }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}
          SNOWSQL_SCHEMA: ${{ secrets.SNOWSQL_SCHEMA }}
        run: |
          echo "Executing SnowSQL query..."
          export PATH="/home/runner/snowsql/bin:$PATH"

          snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PASSWORD \
            -d $SNOWSQL_DATABASE -w $SNOWSQL_WAREHOUSE -s $SNOWSQL_SCHEMA \
            -f ./run_query.sql
